import { Check, CheckCircle2, CircleDashed, Copy, Download, Github } from 'lucide-react'
import { useState } from 'react'
import type { Guide } from '../../types/api'

export function GuideView({ data }: { data: Guide }) {
  const [copied, setCopied] = useState(false)
  const sections = [['Overview', data.guide.overview_content], ['Getting started', data.guide.getting_started_content], ['How to contribute', data.guide.how_to_contribute_content], ['Open questions', data.guide.open_questions_content]]
  const copyGuide = async () => { const content = [...sections.map(([title, text]) => `${title}\n${text}`), `Setup checklist\n${data.guide.setup_checklist.map(item => `${item.status === 'found' ? '[ ]' : '[?]'} ${item.label}: ${item.instructions}`).join('\n')}`].join('\n\n'); await navigator.clipboard?.writeText(content); setCopied(true); window.setTimeout(() => setCopied(false), 1800) }
  return <div className="mt-12 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><article className="panel guide-panel"><div className="guide-toolbar"><div><p className="eyebrow">Evidence-bound contributor guide</p><h2 className="mt-3 text-3xl font-medium">A practical map for {data.repository.repository_name}</h2></div><div className="flex gap-2"><button className="icon-button" type="button" onClick={copyGuide} title="Copy guide">{copied ? <Check size={15}/> : <Copy size={15}/>}</button><button className="icon-button" type="button" onClick={() => window.print()} title="Print guide"><Download size={15}/></button></div></div><section className="project-purpose guide-section"><p className="eyebrow">What this project is</p><p className="purpose-copy">{data.guide.project_description}</p></section><section className="guide-section setup-checklist"><div className="setup-heading"><div><p className="eyebrow">Setup checklist</p><h3 className="mt-2 text-xl font-medium">From clone to first test.</h3></div><span className="record-count">{data.guide.setup_checklist.filter(item => item.status === 'found').length}/{data.guide.setup_checklist.length} signals</span></div><div className="setup-list">{data.guide.setup_checklist.map(item => <div className={`setup-item ${item.status}`} key={item.id}><span className="setup-status">{item.status === 'found' ? <CheckCircle2 size={18}/> : <CircleDashed size={18}/>}</span><div><strong>{item.label}</strong><p>{item.instructions}</p>{item.evidence.length > 0 && <small>Evidence: {item.evidence.join(' · ')}</small>}</div></div>)}</div></section>{sections.map(([title, text]) => <section className="guide-section" key={title}><h3 className="text-lg font-medium">{title}</h3><p className="mt-3 whitespace-pre-line leading-7 text-ink/65">{text}</p></section>)}</article><aside className="panel h-fit p-7"><div className="flex items-center justify-between"><p className="eyebrow">Repository structure</p><span className="record-count">{data.guide.repository_structure.length} paths</span></div><div className="mt-5 space-y-2">{data.guide.repository_structure.map(item => <div className="rounded border border-ink/10 p-3" key={item.file_path}><code className="text-sm text-moss">{item.file_path}</code><p className="mt-1 text-xs text-ink/50">{item.role_description}</p></div>)}</div><div className="mt-7 border-t border-ink/10 pt-5 text-sm text-ink/50"><Github size={15} className="mr-2 inline"/> Source accepted {new Date(data.source_snapshot.accepted_at).toLocaleDateString()}</div></aside></div>
}
