import { Link } from 'react-router-dom'
import { Shell } from '../components/layout/Shell'

export function PrivacyPage() {
  return <LegalLayout eyebrow="RepoMentor / privacy" title="Privacy policy"><p>RepoMentor is designed to help developers understand repository source material. This page explains the information the application handles and how it is used.</p><LegalSection title="Information we handle"><p>RepoMentor may handle account details such as your email address, repository workspace names, GitHub repository URLs, supplied source snapshots, generated guides, notes, and workspace preferences.</p></LegalSection><LegalSection title="How information is used"><p>Information is used to authenticate you, save your workspaces, analyze repository files, generate source guides, and provide the repository browsing experience.</p></LegalSection><LegalSection title="Repository access"><p>When you provide a GitHub repository URL, RepoMentor uses the backend GitHub integration to retrieve repository metadata, README content, directory listings, and selected source files. Repository access is limited to the features required to analyze and display the project.</p></LegalSection><LegalSection title="Local preferences"><p>Some preferences, including theme settings and personal dashboard notes, may be stored locally in your browser. Clear your browser storage to remove locally stored preferences.</p></LegalSection><LegalSection title="Security and retention"><p>Do not add secrets, credentials, or private keys to supplied source material. Production retention, deletion, and hosting policies should be configured by the operator of the deployed RepoMentor instance.</p></LegalSection><p className="legal-note">This is a product template policy and should be reviewed and adapted for your deployment.</p></LegalLayout>
}

export function TermsPage() {
  return <LegalLayout eyebrow="RepoMentor / terms" title="Terms of use"><p>By using RepoMentor, you agree to use the application responsibly and only with repositories and source material you are authorized to inspect.</p><LegalSection title="Acceptable use"><p>You must not use RepoMentor to access, copy, or analyze repositories without permission. Do not use the service to distribute malicious code, credentials, personal data, or content that violates applicable law.</p></LegalSection><LegalSection title="Repository responsibility"><p>You are responsible for the GitHub URLs and source files you submit, as well as confirming that your use of repository content complies with its license and your organization’s policies.</p></LegalSection><LegalSection title="Generated content"><p>RepoMentor generates explanations from available repository evidence. Generated descriptions, architecture notes, and setup guidance should be reviewed by a developer before being treated as authoritative.</p></LegalSection><LegalSection title="Availability"><p>Features may depend on GitHub availability, API rate limits, configured integrations, and the deployment environment. No uninterrupted availability is guaranteed.</p></LegalSection><LegalSection title="Changes"><p>These terms may be updated as RepoMentor evolves. Continued use after an update means you accept the revised terms.</p></LegalSection><p className="legal-note">This is a product template agreement and should be reviewed by the operator before production use.</p></LegalLayout>
}

function LegalLayout({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) {
  return <Shell><article className="legal-page"><Link to="/" className="text-link">← Back to RepoMentor</Link><p className="eyebrow legal-eyebrow">{eyebrow}</p><h1>{title}</h1><div className="legal-copy">{children}</div></article></Shell>
}

function LegalSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2>{title}</h2>{children}</section> }
