import { useEffect, useMemo, useState } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { Bookmark, Clock3, FileText, Github, ListChecks, NotebookPen, Plus, ArrowUpRight } from 'lucide-react'
import { Shell } from '../components/layout/Shell'
import { useWorkspaces } from '../hooks/useWorkspaces'
import { useAppState } from '../state/AppState'
import type { Workspace } from '../types/api'

type PersonalState = { bookmarkedFiles: string[]; bookmarkedIssues: string[]; notes: string; recent: string[]; progress: Record<string, number> }

const initialState: PersonalState = { bookmarkedFiles: [], bookmarkedIssues: [], notes: '', recent: [], progress: {} }

export function MyWorkspacePage() {
  const { state } = useAppState()
  const { data: workspaces = [], isLoading } = useWorkspaces()
  const storageKey = `repomentor-personal-${state.authEmail || 'guest'}`
  const [personal, setPersonal] = useState<PersonalState>(() => { try { return { ...initialState, ...JSON.parse(localStorage.getItem(storageKey) || '{}') } } catch { return initialState } })
  useEffect(() => { localStorage.setItem(storageKey, JSON.stringify(personal)) }, [personal, storageKey])
  const recent = useMemo(() => personal.recent.map(id => workspaces.find(workspace => workspace.id === id)).filter(Boolean) as Workspace[], [personal.recent, workspaces])
  if (!state.authEmail) return <Navigate to="/login" state={{ from: '/my-workspace' }} replace />
  const totalProgress = workspaces.length ? Math.round(workspaces.reduce((sum, workspace) => sum + (personal.progress[workspace.id] || (workspace.state === 'guide_generated' ? 100 : workspace.source_file_count ? 60 : 20)), 0) / workspaces.length) : 0
  return <Shell><div className="mx-auto max-w-7xl px-6 py-12 lg:px-10 lg:py-16"><div className="personal-hero"><div><p className="eyebrow">Personal command center</p><h1 className="mt-3">My <em>workspace.</em></h1><p>Everything you have explored, saved, and still want to understand.</p></div><Link className="button-primary" to="/new"><Plus size={16}/> New repository</Link></div><div className="personal-progress panel"><div><p className="eyebrow">Onboarding progress</p><h2>{totalProgress}% <span>across your repositories</span></h2></div><div className="progress-track"><span style={{ width: `${totalProgress}%` }}/></div><p className="progress-caption">{workspaces.length ? 'Keep exploring source, guides, and setup details.' : 'Create your first repository workspace to begin.'}</p></div><div className="personal-grid"><DashboardSection icon={<Github size={17}/>} title="Saved repositories" count={workspaces.length}>{isLoading ? <DashboardMessage>Loading your repositories...</DashboardMessage> : workspaces.length ? <div className="personal-list">{workspaces.map(workspace => <WorkspaceRow key={workspace.id} workspace={workspace} progress={personal.progress[workspace.id] || (workspace.state === 'guide_generated' ? 100 : workspace.source_file_count ? 60 : 20)} onOpen={() => setPersonal(current => ({ ...current, recent: [workspace.id, ...current.recent.filter(id => id !== workspace.id)].slice(0, 5) }))}/>)}</div> : <DashboardMessage>No saved repositories yet.<Link to="/new">Create one <ArrowUpRight size={13}/></Link></DashboardMessage>}</DashboardSection><DashboardSection icon={<Clock3 size={17}/>} title="Recently explored projects" count={recent.length}>{recent.length ? <div className="personal-list">{recent.map(workspace => <WorkspaceRow key={workspace.id} workspace={workspace} progress={personal.progress[workspace.id] || 20}/>)}</div> : <DashboardMessage>Your recently opened repositories will appear here.</DashboardMessage>}</DashboardSection><DashboardSection icon={<Bookmark size={17}/>} title="Bookmarked files & issues" count={personal.bookmarkedFiles.length + personal.bookmarkedIssues.length}><DashboardMessage>{personal.bookmarkedFiles.length || personal.bookmarkedIssues.length ? `${personal.bookmarkedFiles.length} files and ${personal.bookmarkedIssues.length} issues bookmarked.` : 'Bookmark important files and GitHub issues while exploring.'}</DashboardMessage></DashboardSection><DashboardSection icon={<NotebookPen size={17}/>} title="Personal notes"><textarea className="notes-input" value={personal.notes} onChange={event => setPersonal(current => ({ ...current, notes: event.target.value }))} placeholder="Capture what you learned, questions to revisit, or setup notes..."/><p className="notes-caption">Saved privately in this browser.</p></DashboardSection></div></div></Shell>
}

function DashboardSection({ icon, title, count, children }: { icon: React.ReactNode; title: string; count?: number; children: React.ReactNode }) { return <section className="personal-section panel"><div className="personal-section-heading"><div><span className="personal-section-icon">{icon}</span><h2>{title}</h2></div>{count !== undefined && <span className="record-count">{count.toString().padStart(2, '0')}</span>}</div>{children}</section> }
function WorkspaceRow({ workspace, progress, onOpen }: { workspace: Workspace; progress: number; onOpen?: () => void }) { return <Link to={`/workspace/${workspace.id}`} onClick={onOpen} className="personal-workspace-row"><span className="personal-repo-mark">{workspace.repository_name.slice(0, 1).toUpperCase()}</span><span className="personal-workspace-copy"><strong>{workspace.repository_name}</strong><small>{workspace.github_repository_url || 'Local source snapshot'}</small></span><span className="personal-workspace-progress"><span><i style={{ width: `${progress}%` }}/></span>{progress}%</span></Link> }
function DashboardMessage({ children }: { children: React.ReactNode }) { return <div className="dashboard-message">{children}</div> }
